### ISSUE TITLE
css section chosen wrong

### ISSUE THREAD

**Issue by s72785** [fsfw-dresden/homepage#43]
was dedicated to themen only, now used in index but css done wrong

``` css
#content-container.nopadding {
    padding-top: 0;
    padding-bottom: 0;
}
```

it should  be either in id or in class to be usable in a modular way
